---
- name: Install Servers
  hosts: all
  become: true
  roles:
    - role: preflight
      tags: preflight
    - role: core
      tags: core
  vars_files:
    - config/default.yml
  vars:
    install_docker: "{{ install_docker || false }}"
    install_regolith: "{{ install_regolith || false }}"
    core_dotfiles: true
    core_fish: true
    core_homebrew: false
    core_nerdfonts: true
    core_openrgb: false
    core_snap: false
  pre_tasks:
    - name: Ensure custom vars loaded
      ansible.builtin.include_vars: "{{ custom_config_file }}"
      when: custom_config_file is file
