---
- name: Ensure fish package installed
  ansible.builtin.package:
    name: "{{ core_fish_packages }}"
    state: present
  tags: fish

- name: Ensure omf install script downloaded
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    dest: /tmp/omf-install.fish
    mode: "0777"
  tags: fish

- name: Ensure omf installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: fish /tmp/omf-install.fish --noninteractive -y --verbose
    creates: "{{ home_dir }}/.config/omf"
  tags: fish

- name: Ensure omf updated
  become: true
  become_user: "{{ user }}"
  tags: fish
  ansible.builtin.command:
    cmd: 'fish -c "omf update"'
  changed_when: false

- name: Ensure omf plugins installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: 'fish -c "omf install {{ item }}"'
    creates: "{{ home_dir }}/.local/share/omf/pkg/{{ item }}"
  with_items: "{{ core_omf_plugins }}"
  tags: fish

- name: Ensure omf themes installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: 'fish -c "omf install {{ item }}"'
    creates: "{{ home_dir }}/.local/share/omf/themes/{{ item }}"
  with_items: "{{ core_omf_themes }}"
  tags: fish

- name: Ensure user shell configured
  ansible.builtin.user:
    user: "{{ user }}"
    state: present
    shell: /usr/bin/fish
  tags: user
