---
- name: Ensure fish package installed
  ansible.builtin.package:
    name: "{{ fish_packages }}"
    state: present
  tags: fish

- name: Ensure omf install script downloaded
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    dest: /tmp/omf-install.fish
    mode: "0777"
  tags: fish

- name: Ensure omf installed
  become: true
  become_user: toni
  ansible.builtin.command:
    cmd: fish /tmp/omf-install.fish --noninteractive -y --verbose
    creates: "{{ home_dir }}/.config/omf"
  tags: fish

- name: Ensure omf updated
  become: true
  become_user: toni
  tags: fish
  ansible.builtin.command:
    cmd: 'fish -c "omf update"'
  changed_when: false

- name: Ensure omf plugins installed
  become: true
  become_user: toni
  ansible.builtin.command:
    cmd: 'fish -c "omf install {{ item }}"'
    creates: "{{ home_dir }}/.local/share/omf/pkg/{{ item }}"
  with_items: "{{ fish_plugins }}"
  tags: fish

- name: Ensure omf themes installed
  become: true
  become_user: toni
  ansible.builtin.command:
    cmd: 'fish -c "omf install {{ item }}"'
    creates: "{{ home_dir }}/.local/share/omf/themes/{{ item }}"
  with_items: "{{ fish_themes }}"
  tags: fish

- name: Ensure nerd fonts unzipped
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
    dest: "{{ home_dir }}/.local/share/fonts"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0666"
    remote_src: yes
    creates: "{{ home_dir }}/.local/share/fonts/HackNerdFontMono-Bold.ttf"
  tags: fish
