---
- name: Ensure cache updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600

- name: Ensure required packages installed
  ansible.builtin.apt:
    name: "{{ core_packages }}"
    state: present
  tags: packages

- name: Ensure user configured
  ansible.builtin.import_tasks: user.yml
  tags: user

- name: Ensure password store configured
  ansible.builtin.import_tasks: pass.yml
  when: preflight_pass_repo != ''
  tags: pass
