---
- name: Ensure cache updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600

- name: Ensure required packages installed
  ansible.builtin.package:
    name: "{{ core_packages }}"
    state: present

- name: Ensure user configured
  ansible.builtin.include_tasks: user.yml
  tags: user
