---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

- name: Import main playbook
  import_playbook: ../../main.yml
  tags: [preflight, core]
