---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: Ensure apt proxy configured
      ansible.builtin.template:
        src: "99-proxy.conf.j2"
        dest: "/etc/apt/apt.conf.d/99-proxy.conf"
        mode: "0775"
        owner: "root"
        group: "root"
      when: lookup('ansible.builtin.env', 'HTTP_PROXY') != ''

- name: Import main playbook
  ansible.builtin.import_playbook: ../../main.yml
