---
name: Testing

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: ["main"]

  schedule:
    - cron: "0 16 * * *"

jobs:
  testing:
    uses: kilip/gh-common/.github/workflows/ansible-testing.yml@main
    with:
      dists: ubuntu-22.04, debian-12
    secrets: inherit
